using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebUI.Models
{
    /// <summary>
    /// This class stores information about a post in a social network,
    /// containing the common properties such as a username, timestamp,
    /// likes, comments and more. It acts as a superclass for the
    /// MessagePost and PhotoPost classes.
    /// </summary>
    /// <author>
    /// Jason Huggins (modified 18/03/2021)
    /// </author>
    [Serializable]
    public class Post
    {
        // Primary key (auto-generated by database)
        public int PostID { get; set; }

        [StringLength(20), Required]
        public string Username { get; set; }

        public DateTime Timestamp { get; set; }

        public int Likes { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }

        /// <summary>
        /// Constructor initialising values.
        /// </summary>
        public Post()
        {
            Timestamp = DateTime.Now;
            Likes = 0;
        }

        /// <summary>
        /// Record one more 'Like' indication from a user.
        /// </summary>
        public void Like()
        {
            Likes++;
        }

        ///<summary>
        /// Record that a user has withdrawn his/her 'Like' vote.
        ///</summary>
        public void Unlike()
        {
            if (Likes > 0)
            {
                Likes--;
            }
        }

        ///<summary>
        /// Create a string describing a time point in the past in terms 
        /// relative to current time, such as "30 seconds ago" or "7 minutes ago".
        /// Currently, only seconds and minutes are used for the string.
        /// </summary>
        /// <returns>
        /// A relative time string for the given time
        /// </returns>      
        public String FormatElapsedTime()
        {
            DateTime current = DateTime.Now;
            TimeSpan timePast = current - Timestamp;

            long seconds = (long)timePast.TotalSeconds;
            long minutes = seconds / 60;

            if (minutes > 0)
            {
                return minutes + " minutes ago";
            }
            else
            {
                return seconds + " seconds ago";
            }
        }
    }
}
